# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown

collections:
  - features
  - apps

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

exclude:
  - '*.config.js'
  - 'package*.json'
  - 'assets'
  - 'node_modules'
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock

plugins:
  - jekyll-sitemap

google_analytics: UA-66914824-1
